### PR TITLE
[GreyVest] Add ErrorBlock component

### PR DESCRIPTION
**Pull request by michsa**
Turn ErrorList into a list of fancy ErrorBlocks by passing it the `block` flag:

```jsx
<ErrorList block>{etc}</ErrorList>
```

This is intended to be used in the Errors autoform component in bid-search, so we can have nice-looking submitError messages 🙂

## Demos

Single error: 
Screen Shot 2019-06-05 at 2 51 35 PM

Multiple errors:
Screen Shot 2019-06-05 at 3 07 36 PM

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>The changelog has not been updated. Please update the changelog.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The version was not updated. Please update the version.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: a4a254f377d919bdcd1be140887acb900cf5b0c7


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 76b350a0ad94ef9bd79562ad7ea7c2c8e86cc444
</p>

**Comment by stellarhoof** [comment]
Waiting on feedback from @carstenux since we should just use only one error component

**Comment by daedalus28** [comment]
If the design is approved, we would probably want to just add the icon and stuff to the existing `ErrorText` component. Then it will magically be added everywhere

**Comment by michsa** [comment]
The idea was that `ErrorText` would continue to be used for field errors, and `ErrorBlock` would be used for submit errors. I did try the block styling on a form field error, and it was a bit much.

Also, maybe worth noting that the text inside `ErrorBlock` is actually an `ErrorText` element itself (at least for now)! It actually uses `ErrorList` internally, so it even supports passing multiple errors to a single block.

I added the flag to `ErrorList` so we don't have to export anything else, and magically adding it everywhere isn't a problem: just stick a `block` flag in the `ErrorList` that `SubmitErrors` is already using 🙂

**Comment by daedalus28** [comment]
> The idea was that `ErrorText` would continue to be used for field errors, and `ErrorBlock` would be used for submit errors. I did try the block styling on a form field error, and it was a bit much.
> 
> Also, maybe worth noting that the text inside `ErrorBlock` is actually an `ErrorText` element itself (at least for now)! It actually uses `ErrorList` internally, so it even supports passing multiple errors to a single block.
> 
> I added the flag to `ErrorList` so we don't have to export anything else, and magically adding it everywhere isn't a problem: just stick a `block` flag in the `ErrorList` that `SubmitErrors` is already using 🙂

Makes sense. Sold 😄

**Pull request merged**
