### PR TITLE
Default to react-icons, fallback to material

### PR DESCRIPTION
**Pull request by Akrion**
- Defaults to `react-icons`
- Keeps `material-icons` support just in case

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 8f7687cc89df2a338ddee123f572ba98388e4970


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 31b75f9fe226dc9014a7a4cf3576790176c47556
</p>

**Comment by stellarhoof** [comment]
I thought we were going to use theming to provide the needed icons.

**Comment by Akrion** [comment]
> I thought we were going to use theming to provide the needed icons. Why take a dependency on react-icons?

I must have missed the memo. Let's discuss this after the standup so I can catch up.

**Comment by rma4ok** [comment]
@Akrion I though we want to do this on spark side and pass new Icon component through the contexture-react theme. We are moving out from GreyVest, so no need to change anything there

**Comment by Akrion** [comment]
f

**Pull request closed without merging**
