### PR TITLE
[feature] ResultTable: Theming base table components

### PR DESCRIPTION
**Pull request by rma4ok**
* [x] ResultTable: extending the theme to utilize base table components such as `Tr`, `Th`, `Td`, `Thead`, `Tbody`

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: cecb72d36d330dd199227602d726bd279a74d2b9


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 80c04196bf37bd7032b2bc5c3aa26c3c2eb95b7b
</p>

**Review by stellarhoof — COMMENTED** [review]
Flawless Victory!

**Review by stellarhoof — APPROVED** [review]

**Comment by stellarhoof** [comment]
@rma4ok This looks pretty good why is it draft?

**Comment by rma4ok** [comment]
@stellarhoof I've changed the way we fallback to built-in components by putting them into the default theme

**Review by stellarhoof — APPROVED** [review]

**Pull request merged**
