### PR TITLE
Theme refactor: cleanup

### PR DESCRIPTION
**Pull request by michsa**
I'm sorry but it had to be done
(Branched from #299)

This PR alters the directory structure of contexture-react, shuffling around the majority of its components in the process.

Before:
```sh
src/
|-- layout/
|   |-- index.js  # base theme & layout component exports
|   `-- ...       # all the layout components
`-- themes/
    |-- blueberry/
    |   |-- index.js  # blueberry theme & component exports
    |   `-- ...       # all the blueberry components
    `-- greyVest/
        |-- index.js  # greyVest theme & component exports
        `-- ...       # all the greyVest components
```

After:
```sh
src/
|-- blueberry/
|   `-- ...  # blueberry component library
|-- greyVest/
|   `-- ...  # greyVest component library
|-- layout/
|   `-- ...  # layout component library
`-- themes/
    |-- base/
    |   |-- index.js  # base theme (imports from '.' and '../../layout')
    |   `-- ...       # components only used for base theme
    |-- blueberry/
    |   |-- index.js  # blueberry theme (imports from '.' and '../../blueberry')
    |   `-- ...       # components only used for blueberry theme
    `-- greyVest/
    |   |-- index.js  # greyVest theme (imports from '.' and '../../greyVest')
    |   `-- ...       # components only used for greyVest theme

```

This is 100% guaranteed to cause giant merge conflicts for any changes we'd wanna make to #299 and pull forward, so... hope there aren't any of those left 😂

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>The changelog has not been updated. Please update the changelog.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>The version was not updated. Please update the version.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Your PR has lint warnings. Please consider fixing these.
      
<details>
  <summary>QueryBuilder.js</summary>
  <p><a href="https://github.com/smartprocure/contexture-react/blob/feature/theme-refactor-cleanup/src/queryBuilder/QueryBuilder.js" target="_blank">src/queryBuilder/QueryBuilder.js</a></p>
  
  <strong>Unexpected console statement.</strong>
  <code>Line 22: console.log('queryBuilder theme', theme)</code>
</details>
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>You reduced the total lines of code! Awesome! :+1:</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 2f429d1ea796a9267c64136eb7cade383833f334


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 31858543fc0aa68e43463d4b958d5a615b79c64d
</p>

**Comment by stellarhoof** [comment]
What was wrong with the previous layout?

**Comment by michsa** [comment]
@stellarhoof Nothing's wrong with it - it's just that with the new theme stuff, there's a fairly important distinction between "component libraries" and "themes", and the new structure better reflects that. 

Specifically, component libraries (eg src/greyVest/) are namespaced collections of components, while themes (eg src/themes/greyVest) import a subset of their corresponding library and export a theme object to be used with ThemeProvider.

If we decide to break up contexture-react in the future, we'd do it by splitting off the component libraries into their own repo, and having contexture-react depend on it - so this layout also facilitates that outcome. 🙂

**Comment by stellarhoof** [comment]
I see. I like the idea of making a distinction between the component library and everything else. However, I think this PR can go even further by having a single directory combining all the components used by blueberry and greyvest. Then we can use css in js to export styled components from the themes. We can also do it immediately after this PR but then you'd be shuffling more files around.

**Pull request merged**
